[package]
name = "jna-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.19.0"
once_cell = "1.10.0"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
log = "0.4.16"
dotenv = "0.15.0"
simplelog = "0.11.2"
